Models/ServicePlan.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace FirstApp.Models
{
    public class ServicePlan : BaseModel
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Key { get; set; }
        public long ServiceId { get; set; }
        //[ForeignKey("ServiceId")]
        public virtual Service Service { get; set; }
        public double Price { get; set; }
        public string CommissionType { get; set; }
        public double Commission { get; set; }
        public double ConvienceFee { get; set; }
        public Boolean IsDefault { get; set; }
    }
}

Controllers/ServicePlanController.cs
using System.Linq;
using FirstApp.Models;
using FirstApp.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;


namespace FirstApp.Controllers {

    [Authorize]
    [Route("services/plan")]
    [ApiExplorerSettings(IgnoreApi = true)]
    public class ServicePlanController : Controller {

        private readonly DBDataContext _DB;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        //private readonly RoleManager<ApplicationUser> _roleManager;
        private readonly ILogger _logger;

        private readonly IConfiguration _configuration;


        public ServicePlanController (
            DBDataContext DB,
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signinManager,
            ILoggerFactory loggerFactory,
            IConfiguration configuration
         )
        {
            _configuration = configuration;
            _DB = DB;
            _userManager = userManager;
            _signInManager = signinManager;
            //_roleManager = roleManager;
            _logger = loggerFactory.CreateLogger<AccountController>();
        }

        [HttpGet]
        [Route("hidden")]
        public IActionResult Index(){
            return View();
        }

        [HttpGet]
        [Route("create")]
        public IActionResult Create(){
            var service = new CreateServicePlanVM();
            return View(service);
        }

        [HttpPost]
        public IActionResult Create(CreatePaymentPlanVM plan){

            return View();
        }
        
        [HttpGet]
        [Route("edit")]
        public IActionResult Update(int PlanId){

            var service = _DB.Services.FirstOrDefault(x => x.Id == PlanId);
            
            return View("New", service);
        }
    }
}

Views/ServicePlan/Create.cshtml
@model FirstApp.Models.ViewModels.CreateServicePlanVM
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"
@{
    Layout = "_Dashboard";
}

@section Title {
<title>Biller.ng - Service Plan </title>
}



<nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
        <li><a href="/">Home</a></li>
        <li class="is-active"><a href="#" aria-current="page">Service Plan</a></li>
    </ul>
</nav>

<div class="level mt-2 mr-2 content-title">
    <div class="level-left">
        <div class="level-item">
            <div class="title has-text-primary">


                <span>Service Plan</span>
            </div>
        </div>
    </div>
    <div class="level-right">
        <div class="level-item">
            @*<button type="button" class="button is-small">March 8, 2017 - April 6, 2017</button>*@
        </div>
    </div>
</div>




        @*<a class="button is-link">
    <span class="icon is-small"> <i class="fa fa-plus"></i> </span><span>Add New </span>
</a>*@


<div class="content">


    <div class="columns">
        <div class="column">

        </div>
        <div class="column is-three-fifths">
            <div class="card">
                <div class="card-content">
                    <form role="form" asp-controller="ServicePlan" asp-action="Create" method="post">

                        <div asp-validation-summary="ModelOnly" class="notification is-danger"></div>

                        <div class="field">
                            <label asp-for="Name" class="label"></label>
                            <div class="control">
                                <input asp-for="Name" class="input" placeholder="Service Plan">
                            </div>
                            <span asp-validation-for="Name" class="help is-danger"></span>
                        </div>

                        <div class="field">
                            <label asp-for="Key" class="label"></label>
                            <div class="control">
                                <input asp-for="Key" class="input"  placeholder="Service Identifier">
                            </div>
                            <span asp-validation-for="Key" class="help is-danger"></span>
                        </div>

                        <div class="field">
                            <label asp-for="ServiceId" class="label"></label>
                            <div class="control">
                                <input asp-for="ServiceId" class="input"  placeholder="Service Type">
                            </div>
                            <span asp-validation-for="ServiceId" class="help is-danger"></span>
                        </div>

                        <div class="field is-grouped is-pulled-right">
                            <div class="control">
                                <button class="button is-primary">Save</button>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="column">

        </div>

    </div>
</div>